export const SET_ACTIVE_PATIENT = 'app/SET_ACTIVE_PATIENT';
export const SET_COLLAPSE_MODE = 'app/SET_COLLAPSE_MODE';
export const SET_PRESENT_PATIENTS = 'app/SET_PRESENT_PATIENTS';
export const SET_QUITTING_PATIENTS = 'app/SET_QUITTING_PATIENTS';